### ISSUE TITLE
eigenstates version fails on plain installation

### ISSUE THREAD

**Issue by 2colours** [lizmat/Ecosystem#1]
Hello,

when I try to install the module on an empty setup, I reach the following point with the installation:
```
===> Testing: Ecosystem:ver<0.0.16>:auth<zef:lizmat>
[Ecosystem] # Failed test 'is use-target ok?'
[Ecosystem] # at t/01-basic.rakutest line 23
[Ecosystem] # expected: 'eigenstates:ver<0.0.9>:auth<zef:lizmat>'
[Ecosystem] #      got: 'eigenstates:ver<0.0.10>:auth<zef:lizmat>'
[Ecosystem] # Failed test 'is resolve ok?'
[Ecosystem] # at t/01-basic.rakutest line 43
[Ecosystem] # expected: 'eigenstates:ver<0.0.9>:auth<zef:lizmat>'
[Ecosystem] #      got: 'eigenstates:ver<0.0.10>:auth<zef:lizmat>'
[Ecosystem] # You failed 2 tests of 12
```

It seems that eigenstates version is hardcoded - I couldn't find the dependency chain that installs it at all - and it got updated since the test version.
What do you think could be a long-term solution to this?

Environment: moar-2022.07 of rakubrew, on Ubuntu 20.04.

**Comment by lizmat** [comment]
Thanks for the report!

Version 0.17 uploaded to zef ecosystem.  `zef update && zef install Ecosystem` should do the trick now.

**Comment by arkiuat** [comment]
I'm having this same issue again, except that now it looks like the below. I've also tried installing with only eigenstates:ver<0.0.11> installed, and with only eigenstates:ver<0.0.12> installed, and get the exact same result in all three cases.

Environment: moar-2025.10 of rakubrew, on MacOS Sequoia 15.7.1 (Darwin 24.6.0 ARM64)

===> Testing: Ecosystem:ver<0.0.31>:auth<zef:lizmat>
[Ecosystem] # Failed test 'is use-target ok?'
[Ecosystem] # at t/01-basic.rakutest line 23
[Ecosystem] # expected: 'eigenstates:ver<0.0.11>:auth<zef:lizmat>'
[Ecosystem] #      got: 'eigenstates:ver<0.0.12>:auth<zef:lizmat>'
[Ecosystem] # Failed test 'is resolve ok?'
[Ecosystem] # at t/01-basic.rakutest line 43
[Ecosystem] # expected: 'eigenstates:ver<0.0.11>:auth<zef:lizmat>'
[Ecosystem] #      got: 'eigenstates:ver<0.0.12>:auth<zef:lizmat>'
[Ecosystem] # Failed test 'found the EIGENSTATES tag'
[Ecosystem] # at t/01-basic.rakutest line 47
[Ecosystem] # expected: 'eigenstates:ver<0.0.11>:auth<zef:lizmat>'
[Ecosystem] #      got: 'eigenstates:ver<0.0.12>:auth<zef:lizmat>'
[Ecosystem] # You failed 3 tests of 16
===> Testing [FAIL]: Ecosystem:ver<0.0.31>:auth<zef:lizmat>
Aborting due to test failure: Ecosystem:ver<0.0.31>:auth<zef:lizmat> (use --force-test to override)
(1)% zef list --installed | grep eigenstates
===> Found via inst#/Users/arkiuat/.rakubrew/versions/moar-2025.10/share/perl6/core
===> Found via inst#/Users/arkiuat/.rakubrew/versions/moar-2025.10/share/perl6/site
eigenstates:ver<0.0.11>:auth<zef:lizmat>
eigenstates:ver<0.0.12>:auth<zef:lizmat>
%

**Comment by lizmat** [comment]
Thanks for the headsup!

Argh, yes a new release of `eigenstates` borked the test here.  I thought that would be a relatively stable module, so a good test target.  Guess  I outsmarted myself.

Just uploaded 0.0.32 to fez, should be available soon!

**Comment by arkiuat** [comment]
> Just uploaded 0.0.32 to fez, should be available soon!

Thanks! 0.0.32 installed just fine.
